### ISSUE TITLE
Put reprof repo (removing svn structure)

### ISSUE THREAD

**Issue by juanmirocks** [Rostlab/reprof#1]
@rocreguant @ccmoratilla 

(The removing of the svn structure may be also relevant for @leidigl and @seitza )
- [x] Notify @jmcejuela when you are ready to remove the PROFsec repo. Or otherwise, let me know if you think we must keep both repositories.

**Comment by rocreguant** [comment]
You've been notified in Rostlab/PROFsec#2. PROFsec can be deleted.
Closing this issue
