### ISSUE TITLE
Output directory cannot be selected even if documented as such

### ISSUE THREAD

**Issue by juanmirocks** [Rostlab/reprof#3]

**Comment by rocreguant** [comment]
*only for the code execution with mutations

**Comment by juanmirocks** [comment]
@rocreguant if you can indeed fix the bug in the perl script that would be great

**Comment by juanmirocks** [comment]
Remember to start all your changes in the develop branch

**Comment by rocreguant** [comment]
My bad, I wrote a wrong command and forgot to put "-o" in front of the output path
