### ISSUE TITLE
Register on Elixir

### ISSUE THREAD

**Issue by juanmirocks** [Rostlab/reprof#4]
- [ ] Register
- [ ] Put link in README header

**Comment by rocreguant** [comment]
Don't we also need to create some kind of github wiki?
Wasn't it until February 4th?

**Comment by juanmirocks** [comment]
Upload your final presentation's slides to the wiki. Besides, you could also link on the wiki any possible rostlab page of the tool or other detailed information. More is not necessary.

Where you thinking of sth else?

Yes, you have until Feb 4th for the remaining issues.

**Comment by rocreguant** [comment]
No, that was it.
We'll do it after the exam.

**Comment by ccmoratilla** [comment]
We are done with the repository, wiki, and Elixir.
 :)

**Comment by juanmirocks** [comment]
Thanks Cristina. I miss to see the elixir link on the README and the slides on the wiki ?

**Comment by rocreguant** [comment]
What do you mean the slides on the wiki? Is it this https://github.com/Rostlab/reprof/wiki/Description ??
I just changed the README as requested.

**Comment by juanmirocks** [comment]
I mean your actual final presentation's slides (pdf? google drive? pptx?)

**Comment by rocreguant** [comment]
Done! :)
I've added the google drive link to the slides at the end of https://github.com/Rostlab/reprof/wiki/Description

**Comment by juanmirocks** [comment]
Awesome :)
