### ISSUE TITLE
Error running sudo make-ssl-cert

### ISSUE THREAD

**Issue by juanmirocks** [Rostlab/reprof#5]
``` shell
$ sudo make-ssl-cert
Usage: /usr/sbin/make-ssl-cert template output [--force-overwrite]
Usage: /usr/sbin/make-ssl-cert generate-default-snakeoil [--force-overwrite]
```

Furthermore in my Vagrant image (`config.vm.box = "debian/wheezy64"`), I had to install package `ssl-cert` to have the program `make-ssl-cert`

**Comment by juanmirocks** [comment]
Note that despite this error, I can perfectly run the tool with the provided instructions. Good job!

Is the `make-ssl-cert` necessary?

**Comment by rocreguant** [comment]
you're right. It's not necessary.
I did just check it in a clean installation.
